name: Build for TVBox

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Optional message for the run'
        required: false
        default: 'Manual run'
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CheckOut Code
        uses: actions/checkout@v3
      - name: Set Up NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r18b
          local-cache: true
      - name: Build
        run: |
          cd /home/runner/work/android-udpxy/android-udpxy/jni
          ndk-build
          ls /home/runner/work/android-udpxy/android-udpxy/
  
      - name: Save Exec
        uses: actions/upload-artifact@v4
        with:
          name: Udpxy
          path: /home/runner/work/android-udpxy/android-udpxy/libs
